name: build-test 

on:
  push:
    tags:
      - '**'
    branches:
      - '**'
  pull_request:

jobs:

  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go:
          - '1.18'
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: ${{ matrix.go }}
        stable: false

    - name: Build
      run: go build -v ./... 

    - name: Test
      run: go test -v -coverprofile=coverage.out -covermode=atomic ./...

    - name: Codecov
      uses: codecov/codecov-action@v5
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        file: ./coverage.out
        flags: unittests
        verbose: true
      if: matrix.go == '1.18'
